# -*- mode: ruby -*-
# vi: set ft=ruby :



NODES = [
    { :hostname => "firstvm", :ip => "172.20.11.10", :prov => "provision1.sh" },
    { :hostname => "secondvm", :ip => "172.20.11.11", :prov => "provision2.sh" }
]

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  NODES.each do |node|
    config.vm.define node[:hostname] do |machine|
      machine.vm.network "private_network", ip: node[:ip]
      machine.vm.provision "shell", path: node[:prov]
      machine.vm.provider "virtualbox" do |vb|
        vb.name = node[:hostname]
        vb.gui = true
        vb.memory = "2048"
        vb.cpus = 1
      end
    end
    config.vm.usable_port_range = 8000..8999
    config.vm.network "forwarded_port", guest: 80, host: 8086,
      auto_correct: true
  end
end