# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "firstvm" => "172.20.11.10",
  "secondvm" => "172.20.11.11"
}

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.network "private_network", ip: ip
      machine.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.gui = true
        vb.memory = "2048"
        vb.cpus = 1
      end
    end
    config.vm.usable_port_range = 8000..8999
    config.vm.network "forwarded_port", guest: 80, host: 8086,
      auto_correct: true
    config.vm.provision "shell", path: "provision.sh"
  end
end